Feature curd singer
awesome-academy/imusic_awesome_01 pull request #8
Opened 2019-04-17 14:17 UTC by doanhvv

## About 
- Tính năng thêm, sửa, xóa, phân trang cho singer.

## Change UI:
![image](https://user-images.githubusercontent.com/43636727/56294935-2194ea80-6156-11e9-801e-7f0a5fe01cfe.png)
![image](https://user-images.githubusercontent.com/43636727/56294955-2c4f7f80-6156-11e9-9ddf-8c25633f2085.png)
![image](https://user-images.githubusercontent.com/43636727/56294977-383b4180-6156-11e9-9d28-c05440dad7d3.png)

2019-04-18 01:00 UTC, mytv01-1146 commented on public/js/sites/singer.js
> +    mixins: [mixin],
Bỏ demo đi

2019-04-18 01:00 UTC, mytv01-1146 commented on resources/views/admin/modules/singer/form.blade.php
> +{{-- {!! $singer !!} --}}
xóa đi

2019-04-18 01:00 UTC, mytv01-1146 commented on resources/views/admin/modules/singer/form.blade.php
> +
bỏ dòng trắng đi

2019-04-18 01:00 UTC, mytv01-1146 commented on routes/api.php
> +Route::get('singers/getListSinger', 'Admin\SingerController@getListSinger');
Cái này có cần dùng đến ko

2019-04-18 01:04 UTC, mytv01-1146 commented on app/Http/Controllers/Admin/SingerController.php
> +        return response()->json(['msg' => 'Error']);
sao msg lại là error

2019-04-18 01:04 UTC, mytv01-1146 commented on app/Http/Controllers/Admin/SingerController.php
> +        $singer = $this->singerRepository->update($singer, [
em đặt biến để làm gì

2019-04-18 01:04 UTC, mytv01-1146 commented on public/js/sites/singer-form.js
> +            }
```js
var option = {
                    method: 'POST',
                    url: '/admin/singers',
                    params: this.singer,
                    json: true
                }  
if (this.id) {
 var option = {
                    method: 'PATCH',
                    url: '/admin/singers/'+ this.id,
                    params: this.singer,
                    json: true
                }
}
```

2019-04-18 01:04 UTC, mytv01-1146 commented on public/js/sites/singer-form.js
> +                this.handleError(error.response.status);
1 là dùng this , 2 là dùng sefl.

2019-04-18 01:04 UTC, mytv01-1146 commented on public/js/sites/singer.js
> +            var sefl = this;
bỏ sefl đi

2019-04-18 01:05 UTC, mytv01-1146 requested changes
Gộp commit lại nhé

2019-04-19 12:24 UTC, tranvanmy approved these changes

2019-04-19 12:24 UTC, merged